language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - "pip install --no-binary :all: -r testrequirements.txt"
  - pip install -e .

script: "trial buildbot_UnrealEngine.test"
